# This is a basic workflow to help you get started with Actions

name: VM Automation CI Pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      TF_VAR_azure_subscription_id: ${{ secrets.SUBSCRIPTIONID }}
      TF_VAR_azure_client_id: ${{ secrets.CLIENTID }}
      TF_VAR_azure_client_secret: ${{ secrets.CLIENTSECRET }}
      TF_VAR_azure_tenant_id: ${{ secrets.TENANTID }}
    steps:        
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      # - name: Terraform Initialization
      #   run: terraform init

      # - name: Terraform Plan
      #   run: terraform plan

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve

      - name: Install Packer
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install packer
      
      - name: Packer Check
        run: packer --version

      - name: Packer Init
        run: packer init packer-template.pkr.hcl

      - name: Packer Format
        run: packer fmt packer-template.pkr.hcl

      - name: Packer Validate
        run: packer validate packer-template.pkr.hcl

      # - name: Packer Build
      #   run: packer build packer-template.pkr.hcl